---
    - name: install mariadb
      apt:
        name:
          - mariadb-server
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
