---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Java (if not installed)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install apt package requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gpg-agent
    - curl
    - procps
    - net-tools
    - gnupg

- name: Install Elasticsearch
  block:
    - name: elasticsearch-install | Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"

    - name: Add Elasticsearch APT Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: "elastic-8.x.list"

    - name: Install Elasticsearch package
      ansible.builtin.apt:
        name: elasticsearch
        state: present

- name: Update Elasticsearch Configuration File
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^network\\.host:', line: 'network.host: {{ inventory_hostname }}' }
    - { regexp: '^http\\.port:', line: 'http.port: {{ elasticsearch.http_port }}' }

- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
